---
database:
  host: localhost
  name: "{{ site.domain.replace('.', '_') }}"
  sub_name: "{{ site.domain.replace('.', '_') }}_{{ site.subdomain | default('sub') }}"
  username: "{{ site.domain.replace('.', '_') }}"
  password: "{{ lookup('password', playbook_dir + '/credentials/' + site.domain + '/database.txt chars=ascii_letters,digits length=20') }}"
  type: mysql
