---
- name: Creating site directory
  file: path={{ site_directory }}/site
        state=directory
        mode=0775

- name: Creating cache directory
  file: path={{ site_directory }}/site/cache
        state=directory
        mode=0775

- name: Uploading site data
  copy: src={{ local_site_directory }}/data
        dest={{ site_directory }}/site

- name: Uploading site scripts
  copy: src={{ local_site_directory }}/scripts
        dest={{ site_directory }}/site

- name: Uploading site styles
  copy: src={{ local_site_directory }}/styles
        dest={{ site_directory }}/site

- name: Uploading site templates
  copy: src={{ local_site_directory }}/templates
        dest={{ site_directory }}/site

- name: Uploading site configuration file
  copy: src={{ local_site_directory }}/config.php
        dest={{ site_directory }}/site/config.php

- stat: {{ inventory_dir + '/credentials/' + site.domain + '/backend.txt' }}
  register: backend_password_file

- name: Generating backend password
  command: {{ cat /usr/share/dict/words | perl -MList::Util -e "print List::Util::shuffle <>" | head -n 3 | tr "\\n" " " > inventory_dir + '/credentials/' + site.domain + '/backend.txt' }}
  when: backend_password_file.stat.exists == False

- name: Configuring backend password
  lineinfile: dest={{ site_directory }}/site/data/system_init.xml
              regexp="^\s*password=\"\""
              line="		password=\"{{ lookup('file', inventory_dir + '/credentials/' + site.domain + '/backend.txt') }}\""

- name: Configuring time zone
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^define\('_TIMEZONE', '.*'\);"
              line="define('_TIMEZONE', '{{ timezone }}');"

- name: Configuring database host
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'host'\s=>\s'.*',"
              line="		'host' => '{{ database.host }}',"

- name: Configuring database username
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'user'\s=>\s'.*',"
              line="		'user' => '{{ database.username }}',"

- name: Configuring database password
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'pass'\s=>\s'.*',"
              line="		'pass' => '{{ database.password }}',"

- name: Configuring database name
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'name'\s=>\s'.*'"
              line="		'name' => '{{ database.name }}'"

