---
- name: Creating site directory
  file: path={{ site_directory }}/site
        state=directory
        mode=0775

- name: Clear cache directory
  file: path="{{ site_directory }}/site/cache/"
        state=absent


- name: Check if site scripts need to be uploaded
  local_action: stat path={{ local_site_directory }}/scripts
  register: scripts_directory
  ignore_errors: True

- name: Check if site modules need to be uploaded
  local_action: stat path={{ local_site_directory }}/modules
  register: modules_directory
  ignore_errors: True

- name: Check if site images need to be uploaded
  local_action: stat path={{ local_site_directory }}/images
  register: images_directory
  ignore_errors: True

- name: Check if gallery needs to be uploaded
  local_action: stat path={{ local_site_directory }}/gallery
  register: gallery_directory
  ignore_errors: True


- name: Uploading site data
  copy: src={{ local_site_directory }}/data
        dest={{ site_directory }}/site

- name: Uploading site scripts
  copy: src={{ local_site_directory }}/scripts
        dest={{ site_directory }}/site
  when: scripts_directory.stat.exists

- name: Uploading site speciffic modules
  copy: src={{ local_site_directory }}/modules
        dest={{ site_directory }}/site
  when: modules_directory.stat.exists

- name: Uploading site styles
  copy: src={{ local_site_directory }}/styles
        dest={{ site_directory }}/site

- name: Uploading site templates
  copy: src={{ local_site_directory }}/templates
        dest={{ site_directory }}/site

- name: Uploading site images
  copy: src={{ local_site_directory }}/images
        dest={{ site_directory }}/site
  when: images_directory.stat.exists

- name: Creating gallery directory
  file: path={{ site_directory }}/site/gallery
        state=directory
        mode=0755
  when: gallery_directory.stat.exists

- name: Creating thumbnails directory
  file: path={{ site_directory }}/site/gallery/thumbnails
        state=directory
        mode=0775
  when: gallery_directory.stat.exists

- name: Uploading site gallery
  copy: src={{ local_site_directory }}/gallery/images
        dest={{ site_directory }}/site/gallery
        mode=0775
        force=no
  when: gallery_directory.stat.exists

- name: Uploading site configuration file
  copy: src={{ local_site_directory }}/config.php
        dest={{ site_directory }}/site/config.php
  when: database is defined and timezone is defined

- name: Configuring backend password
  lineinfile: dest={{ site_directory }}/site/data/system_init.xml
              regexp="^\s*password=\"\""
              line="		password=\"{{ backend_password }}\""

- name: Configuring time zone
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^define\('_TIMEZONE', '.*'\);"
              line="define('_TIMEZONE', '{{ timezone }}');"
  when: timezone is defined

- name: Configuring database host
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'host'\s=>\s'.*',"
              line="		'host' => '{{ database.host }}',"
  when: database is defined

- name: Configuring database username for domain
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'user'\s=>\s'.*',"
              line="		'user' => '{{ database.username }}',"
  when: database is defined and site.subdomain is not defined

- name: Configuring database username for subdomain
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'user'\s=>\s'.*',"
              line="		'user' => '{{ database.username }}',"
  when: database is defined and site.subdomain is defined

- name: Configuring database password
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'pass'\s=>\s'.*',"
              line="		'pass' => '{{ database.password }}',"
  when: database is defined

- name: Enabling code optimization
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\$optimize_code\s+=\s+.*;"
              line="$optimize_code = true;"

- name: Configuring database name for domain
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'name'\s=>\s'.*'"
              line="		'name' => '{{ database.name }}'"
  when: database is defined and site.subdomain is not defined

- name: Configuring database name for subdomain
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'name'\s=>\s'.*'"
              line="		'name' => '{{ database.sub_name }}'"
  when: database is defined and site.subdomain is defined
